services:
  - type: web
    name: house-price-api
    env: python
    region: oregon
    runtime: python
    buildCommand: |
      pip install --upgrade pip wheel setuptools
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free